users/config/routes.rb
Rails.application.routes.draw do
  root 'home#index', as: 'home'

  resources :users do
    member do
      get   'topup'
      patch 'topup' => 'users#do_topup'
    end
  end

  resources :orders
  scope :format => true, :constraints => { :format => 'json' } do
    get 'orders'            => 'orders#driver'
    put 'orders/:id/update' => 'orders#update'
  end
  get 'orders/:id/cancel' => 'orders#cancel', as: 'cancel'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

users/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

users/app/models/fleet.rb
class Fleet < ActiveResource::Base
  self.site = "http://localhost:8082"
end

users/app/models/gopay.rb
class Gopay < ActiveResource::Base
  self.site = "http://localhost:8083"
  self.include_format_in_path = false
end

users/app/models/order.rb
class Order < ApplicationRecord
  GMAPS = GoogleMapsService::Client.new(key: 'AIzaSyBtGoQM9mdzHQiyjcxpxfJmSfjK0rUbGEI')

  belongs_to :user
  belongs_to :service

  enum payment_type: {
    "Cash" => "cash",
    "Go-Pay" => "gopay"
  }

  validates :origin, :destination, :payment_type, :state, presence: true
  validates :payment_type, inclusion: payment_types.keys

  validate :validate_locations

  def get_distance
    distance_matrix = GMAPS.distance_matrix(origin, destination)
    distance = distance_matrix[:rows][0][:elements][0][:distance][:value] / 1000.0
    self.distance = distance.to_f.round(1) if distance > 1
    self.distance
  end

  def calculate_price
    price = service.price_per_km * self.distance
    self.price = price.ceil
    self.price
  end

  private

    def validate_locations
      if origin != "" && destination != ""
        distance_matrix = GMAPS.distance_matrix(origin, destination)
        status = distance_matrix[:rows][0][:elements][0][:status]
        if status == "NOT_FOUND"
          errors.add(:origin, "is invalid")
          errors.add(:destination, "is invalid")
        end
      end
    end
end

users/app/models/order_observer.rb
class OrderObserver < ActiveRecord::Observer
  def after_save(order)
    if order.payment_type == "Go-Pay" && order.state == "Completed"
      Gopay.all.each do |gopay|
        @gopay = gopay if gopay.ref_type == "User" && gopay.ref_id == order.user_id
      end
      @gopay.balance -= order.price
    end
  end
end

users/app/models/service.rb
class Service < ApplicationRecord
  has_many :orders

  validates :service_type, :price_per_km, presence: true
  validates :price_per_km, numericality: true
end

users/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  after_create :set_gopay

  has_many :orders

  validates :fullname, presence: true
  validates :phone, presence: true, uniqueness: true, numericality: true, length: {minimum: 10, maximum: 13}
  validates :email, presence: true, uniqueness: true, format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    message: 'has invalid format'
  }
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 8 }, allow_blank: true

  private

    def set_gopay
      Gopay.create(ref_type: "User", ref_id: self.id)
    end
end

users/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize, :set_gopay

  protected

    def authorize
      unless User.find_by(id: session[:user_id])
        redirect_to home_path, notice: 'Please Login'
      end
    end

    def set_gopay
      Gopay.all.each do |gopay|
        @gopay = gopay if gopay.ref_type == "User" && gopay.ref_id == session[:user_id]
      end
    end
end

users/app/controllers/gopays_controller.rb
class GopaysController < ApplicationController
  before_action :set_gopay, except: [:index, :new, :create]

  def index
    @gopays = Gopay.all
  end

  def show
  end

  def topup
  end

  def do_topup
    response = @gopay.gopay.topup(params[:amount])

    respond_to do |format|
      if @gopay.save && response
        format.html { redirect_to topup_gopay_path, notice: 'Top up success.' }
      else
        format.html { redirect_to topup_gopay_path, notice: 'Top up failed: Amount is invalid.' }
      end
    end
  end

  private

    def set_gopay
      @gopay = Gopay.find(params[:id])
    end

    def gopay_params
      params.require(:gopay).permit(:balance, :ref_type, :ref_id)
    end
end

users/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize

  def index
  end
end

users/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :cancel]
  skip_before_action :authorize, only: :index

  def index
    @orders = Order.where("user_id = ?", session[:user_id])
    @all_orders = Order.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @all_orders, only: order_data + [:driver_id] }
    end
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = User.find(session[:user_id])

    @order.distance = @order.get_distance
    @order.price = @order.calculate_price

    respond_to do |format|
      if @order.save
        $rdkafka_producer.produce(payload: @order.to_json, topic: $topic)
        format.html { redirect_to orders_path, notice: 'Thank you for your order.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @order.update(order_params)
  end

  def cancel
    @order.state = "Cancelled"
    @order.save
    redirect_to order_path
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(order_data + [:service_id])
    end

    def order_data
      [:origin, :destination, :payment_type, :distance, :price]
    end
end

users/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
    if session[:user_id]
      redirect_to users_path
    end
  end

  def create
    user = User.find_by(phone: params[:phone])

    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      redirect_to users_path
    else
      redirect_to login_path, notice: 'Invalid phone/password combination'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: 'Logged out'
  end
end

users/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]
  skip_before_action :authorize, only: [:new, :create]
  around_action :rescue_not_found, only: [:do_topup]

  def index
    @users = User.where("id = ?", session[:user_id])
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def topup
  end

  def do_topup
    response = topup_gopay(params[:amount])

    respond_to do |format|
      if response
        format.html { redirect_to topup_user_path, notice: 'Top up success.' }
      else
        format.html { redirect_to topup_user_path, notice: 'Top up failed: Amount is invalid.' }
      end
    end
  end

  def topup_gopay(amount)
    if is_valid?(amount)
      @gopay.balance += amount.to_i
      @gopay.save
    else
      false
    end
  end

  def is_valid?(amount)
    if is_integer?(amount) && amount.to_i > 0
      true
    else
      false
    end
  end

  def is_integer?(amount)
    true if Integer(amount) rescue false
  end

  private

    def rescue_not_found
      yield
    rescue ActiveResource::ResourceNotFound
      redirect_to topup_user_path, notice: 'Top up success.'
    end

    def set_user
      @user = User.find(session[:user_id])
    end

    def user_params
      params.require(:user).permit(:fullname, :phone, :email, :password, :password_confirmation)
    end
end

users/app/helpers/application_helper.rb
module ApplicationHelper
end

users/app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<section>
  <%= image_tag 'GO-PAY.jpg', class: 'mySlides', width: '100%' %>
</section>

<section class="w3-container w3-center w3-content" style="max-width:600px">
  <h2 class="w3-wide">ABOUT GO-JEK</h2>
  <p class="w3-opacity"><i>One App For All Your Needs</i></p>
  <p class="w3-justify">Established in 2010 as a motorcycle ride-hailing phone service, GO-JEK has evolved into an on demand provider of transport and other lifestyle services. Go anywhere easily, quickly, and hassle-free. It’s an easier and more comfortable ride for you and your co-travelers.</p>
</section>

<section class="w3-row-padding w3-center w3-light-grey">
  <article class="w3-third">
    <p>GO-RIDE</p>
    <%= image_tag 'go-ride.svg', alt: 'GO-RIDE', height: '100%' %>
    <p>The first online motorcycle taxi service in Indonesia.</p>
  </article>
  <article class="w3-third">
    <p>GO-CAR</p>
    <%= image_tag 'go-car.svg', alt: 'GO-CAR', height: '100%' %>
    <p>A convenient ride for one passenger or more.</p>
  </article>
  <article class="w3-third">
    <p>GO-PAY</p>
    <%= image_tag 'go-pay.svg', alt: 'GO-PAY', height: '100%' %>
    <p>Easier cashless transactions with range of new features.</p>
  </article>
</section>

users/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  <head>
    <title>GO-JEK Web App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'gojek.png' %>
  </head>

  <body style="padding-bottom:5%">
    <div class="w3-sidebar w3-bar-block w3-black w3-center" style="width:10%">
      <%= link_to (image_tag 'gojek-logo.jpg', width: '95%'), home_path %>
      <a href="/" class="w3-bar-item w3-button">Home</a>
      <% if session[:user_id] %>
        <a href="/users" class="w3-bar-item w3-button">My Account</a>
        <a href="/orders/new" class="w3-bar-item w3-button">Create Order</a>
        <a href="/orders" class="w3-bar-item w3-button">Order History</a>
      <% else %>
        <a href="/users/new" class="w3-bar-item w3-button">Register</a>
      <% end %>
    </div>

    <div style="margin-left:10%">
      <nav class="w3-bar w3-black" style="font-weight:bold">
        <% if session[:user_id] %>
          <a href="/logout" data-method="delete" class="w3-button w3-bar-item" style="float:right">Logout</a>
        <% else %>
          <a href="/login" class="w3-button w3-bar-item" style="float:right">Customer Login</a>
        <% end %>
      </nav>

      <div style="margin:1%">
        <%= yield %>
      </div>
    </div>
  </body>

  <footer class="w3-container w3-center w3-white w3-xlarge footer" style="height:10%">
    <a href="http://facebook.com/gojekindonesia"><i class="fa fa-facebook-official"></i></a>
    <a href="http://twitter.com/gojekindonesia"><i class="fa fa-twitter"></i></a>
    <a href="http://instagram.com/gojekindonesia/"><i class="fa fa-instagram"></i></a>
    <a href="http://youtube.com/channel/UCmlKSK0OKn_B3oPwElW4n5w"><i class="fa fa-youtube"></i></a>
    <p class="w3-medium" style="margin:0">
    © 2017 GO-SCHOLAR Ruby on Rails
    </p>
  </footer>
</html>

users/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div>
      <%= f.label :origin %>
      <%= f.text_field :origin %>
    </div><br>

    <div>
      <%= f.label :destination %>
      <%= f.text_field :destination %>
    </div><br>

    <div>
      <%= f.label :payment_type, 'Payment Type' %>
      <%= f.select :payment_type, Order.payment_types.keys %>
    </div><br>

    <div>
      <%= f.label :service, 'Service Type' %>
      <%= f.collection_select :service_id, Service.all, :id, :service_type %>
    </div><br>

    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>
<br>

users/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>History</h1>

<% if !@orders.blank? %>
  <table style="text-align: center">
    <tr>
      <th width="23%">Service Type</th>
      <th width="23%">State</th>
      <th width="23%">Origin</th>
      <th width="23%">Destination</th>
      <th></th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.service.service_type %></td>
        <td><%= order.state %></td>
        <td><%= order.origin %></td>
        <td><%= order.destination %></td>
        <td>
          <%= link_to 'Details', order %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  Seems you don't have any history.
<% end %>

users/app/views/orders/new.html.erb
<h1>Order GO-JEK</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

users/app/views/orders/show.html.erb
<h1>Order Details</h1>

<p>
  <strong>Service Type:</strong>
  <%= @order.service.service_type %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @order.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @order.destination %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @order.distance %> km
</p>

<p>
  <strong>Payment Type:</strong>
  <%= @order.payment_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@order.price, unit: "Rp ", delimiter: ".", separator: ",") %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @order.driver_name %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<% if @order.state == "Finding Driver" %>
  <p>
    <%= link_to 'Cancel', cancel_path %>
  </p>
<% end %>

<%= link_to 'Back', orders_path %>

users/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div>
      <%= f.label :fullname, 'Name' %>
      <%= f.text_field :fullname %>
    </div><br>

    <div>
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div><br>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div><br>

    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div><br>

    <div>
      <%= f.label :password_confirmation, 'Password Confirmation' %>
      <%= f.password_field :password_confirmation %>
    </div><br>

    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>
<br>

users/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', user_path %>

users/app/views/users/index.html.erb
<h1>Account</h1>

<table style="text-align: center">
  <tr>
    <th width="35%">Customer Name</th>
    <th width="35%">Go-Pay Balance</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.fullname %></td>
      <td><%= number_to_currency(@gopay.balance, unit: "Rp ", delimiter: ".", separator: ",") %></td>
      <td>
        <%= link_to 'Details', user %> |
        <%= link_to 'Top Up Go-Pay', topup_user_path(user) %>
      </td>
    </tr>
  <% end %>
</table>

users/app/views/users/new.html.erb
<h1>Customer Registration</h1>

<%= render 'form', user: @user %>

users/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>User Details</h1>

<p>
  <strong>Name:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Go-Pay:</strong>
  <%= number_to_currency(@gopay.balance, unit: "Rp ", delimiter: ".", separator: ",") %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

users/app/views/users/topup.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Current Balance:</strong>
  <%= number_to_currency(@gopay.balance, unit: "Rp ", delimiter: ".", separator: ",") %>
</p>

<%= form_for user_path, method: :patch do |f| %>
  <fieldset>
    <div>
      <%= f.label :amount %>
      <%= text_field_tag :amount, params[:amount] %>
    </div><br>

    <div>
      <%= f.submit 'Top Up' %>
    </div>
  </fieldset>
<% end %>

<br>

<%= link_to 'Back', users_path %>