drivers/config/routes.rb
Rails.application.routes.draw do
  root 'home#index', as: 'home'

  resources :drivers

  scope :format => true, :constraints => { :format => 'json' } do
    get 'fleets' => 'fleets#index'
  end

  get 'orders' => 'orders#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

drivers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

drivers/app/models/driver.rb
class Driver < ApplicationRecord
  has_secure_password

  after_create :set_gopay

  has_one :fleet
  has_many :orders

  enum service_type: {
    "Go-Ride" => "1",
    "Go-Car" => "2"
  }

  validates :fullname, presence: true
  validates :phone, presence: true, uniqueness: true, numericality: true, length: {minimum: 10, maximum: 13}
  validates :email, presence: true, uniqueness: true, format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    message: 'has invalid format'
  }
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 8 }, allow_blank: true
  validates :service_type, presence: true, inclusion: service_types.keys

  private

    def set_gopay
      gopay = Gopay.create(ref_type: "Driver", ref_id: id)
    end
end

drivers/app/models/driver_observer.rb
class DriverObserver < ActiveRecord::Observer
  def after_create(driver)
    case driver.service_type
    when "Go-Ride"
      service_id = 1
    when "Go-Car"
      service_id = 2
    end
    driver.fleet = Fleet.create(driver_name: driver.fullname, service_id: service_id)
    driver.location = driver.fleet.location
    driver.save
  end

  def after_update(driver)
    Fleet.where(driver_id: driver.id).update(driver_name: driver.fullname)
  end
end

drivers/app/models/fleet.rb
class Fleet < ApplicationRecord
  belongs_to :driver

  validates :driver_name, :service_id, presence: true
  validates :location, presence: true, on: :update
end

drivers/app/models/gopay.rb
class Gopay < ActiveResource::Base
  self.site = "http://localhost:8083"
  self.include_format_in_path = false
end

drivers/app/models/order.rb
class Order < ActiveResource::Base
  self.site = "http://localhost:8081"
end

drivers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize

  protected

    def authorize
      unless Driver.find_by(id: session[:driver_id])
        redirect_to home_path, notice: 'Please Login'
      end
    end
end

drivers/app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]
  before_action :set_gopay
  skip_before_action :authorize, only: [:new, :create]

  def index
    @drivers = Driver.where("id = ?", session[:driver_id])

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @drivers }
    end
  end

  def show
  end

  def new
    @driver = Driver.new
  end

  def edit
  end

  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to login_path, notice: 'Driver was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to driver_path, notice: 'Driver was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

    def set_gopay
      Gopay.all.each do |gopay|
        @gopay = gopay if gopay.ref_type == "Driver" && gopay.ref_id == session[:user_id]
      end
    end

    def set_driver
      @driver = Driver.find(session[:driver_id])
    end

    def driver_params
      params.require(:driver).permit(:fullname, :phone, :email, :password, :password_confirmation, :service_type)
    end
end

drivers/app/controllers/fleets_controller.rb
class FleetsController < ActionController::API
  before_action :set_fleet, except: [:index, :create]

  def index
    @fleets = Fleet.all

    render json: @fleets, only: [:id, :driver_id] + fleet_data
  end

  def show
    render json: @fleet
  end

  def new
    @fleet = Fleet.new
  end

  def edit
  end

  def create
    @fleet = Fleet.new(fleet_params)
  end

  def update
  end

  private

    def set_fleet
      @fleet = Fleet.find(params[:id])
    end

    def fleet_params
      params.permit(fleet_data)
    end

    def fleet_data
      [:driver_name, :service_id, :location]
    end
end

drivers/app/controllers/gopays_controller.rb
class GopaysController < ApplicationController
  before_action :set_gopay, except: [:index, :new, :create]

  def index
    @gopays = Gopay.all
  end

  def show
  end

  private

    def set_gopay
      @gopay = Gopay.find(params[:id])
    end

    def gopay_params
      params.require(:gopay).permit(:balance, :ref_type, :ref_id)
    end
end

drivers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize

  def index
  end
end

drivers/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: :show

  def index
    @orders = Order.all
  end

  def show
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:origin, :destination, :payment_type, :service_id)
    end
end

drivers/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
    if session[:driver_id]
      redirect_to drivers_path
    end
  end

  def create
    driver = Driver.find_by(phone: params[:phone])

    if driver.try(:authenticate, params[:password])
      session[:driver_id] = driver.id
      redirect_to drivers_path
    else
      redirect_to login_path, notice: 'Invalid phone/password combination'
    end
  end

  def destroy
    session[:driver_id] = nil
    redirect_to home_path, notice: 'Logged out'
  end
end

drivers/app/helpers/application_helper.rb
module ApplicationHelper
end

drivers/app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |f| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div>
      <%= f.label :fullname, 'Name' %>
      <%= f.text_field :fullname %>
    </div><br>

    <div>
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div><br>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div><br>

    <div>
      <%= f.label :service_type, 'Service Type' %>
      <%= f.select :service_type, Driver.service_types.keys %>
    </div><br>

    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div><br>

    <div>
      <%= f.label :password_confirmation, 'Password Confirmation' %>
      <%= f.password_field :password_confirmation %>
    </div><br>

    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>
<br>

drivers/app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', driver_path %>

drivers/app/views/drivers/index.html.erb
<h1>Account</h1>

<table style="text-align: center">
  <tr>
    <th width="31%">Driver Name</th>
    <th width="31%">Go-Pay Balance</th>
    <th width="31%">Current Location</th>
    <th></th>
  </tr>
  <% @drivers.each do |driver| %>
    <tr>
      <td><%= driver.fullname %></td>
      <td><%= number_to_currency(@gopay.balance, unit: "Rp ", delimiter: ".", separator: ",") %></td>
      <td><%= driver.location %></td>
      <td>
        <%= link_to 'Details', driver %>
      </td>
    </tr>
  <% end %>
</table>

drivers/app/views/drivers/new.html.erb
<h1>Driver Registration</h1>

<%= render 'form', driver: @driver %>

drivers/app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Driver Details</h1>

<p>
  <strong>Name:</strong>
  <%= @driver.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @driver.phone %>
</p>

<p>
  <strong>Go-Pay:</strong>
  <%= number_to_currency(@gopay.balance, unit: "Rp ", delimiter: ".", separator: ",") %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

drivers/app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<section>
  <%= image_tag 'GO-RIDE.jpg', class: 'mySlides', width: '100%' %>
</section>

<section class="w3-container w3-center w3-content" style="max-width:600px">
  <h2 class="w3-wide">ABOUT GO-JEK</h2>
  <p class="w3-opacity"><i>One App For All Your Needs</i></p>
  <p class="w3-justify">Established in 2010 as a motorcycle ride-hailing phone service, GO-JEK has evolved into an on demand provider of transport and other lifestyle services. Go anywhere easily, quickly, and hassle-free. It’s an easier and more comfortable ride for you and your co-travelers.</p>
</section>

<section class="w3-row-padding w3-center w3-light-grey">
  <article class="w3-third">
    <p>GO-RIDE</p>
    <%= image_tag 'go-ride.svg', alt: 'GO-RIDE', height: '100%' %>
    <p>The first online motorcycle taxi service in Indonesia.</p>
  </article>
  <article class="w3-third">
    <p>GO-CAR</p>
    <%= image_tag 'go-car.svg', alt: 'GO-CAR', height: '100%' %>
    <p>A convenient ride for one passenger or more.</p>
  </article>
  <article class="w3-third">
    <p>GO-PAY</p>
    <%= image_tag 'go-pay.svg', alt: 'GO-PAY', height: '100%' %>
    <p>Easier cashless transactions with range of new features.</p>
  </article>
</section>

drivers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  <head>
    <title>GO-JEK Web App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'gojek.png' %>
  </head>

  <body style="padding-bottom:5%">
    <div class="w3-sidebar w3-bar-block w3-black w3-center" style="width:10%">
      <%= link_to (image_tag 'gojek-logo.jpg', width: '95%'), home_path %>
      <a href="/" class="w3-bar-item w3-button">Home</a>
      <% if session[:driver_id] %>
        <a href="/drivers" class="w3-bar-item w3-button">My Account</a>
        <a href="/orders" class="w3-bar-item w3-button">Job History</a>
      <% else %>
        <a href="/drivers/new" class="w3-bar-item w3-button">Register</a>
      <% end %>
    </div>

    <div style="margin-left:10%">
      <nav class="w3-bar w3-black" style="font-weight:bold">
        <% if session[:driver_id] %>
          <a href="/logout" data-method="delete" class="w3-button w3-bar-item" style="float:right">Logout</a>
        <% else %>
          <a href="/login" class="w3-button w3-bar-item" style="float:right">Driver Login</a>
        <% end %>
      </nav>

      <div style="margin:1%">
        <%= yield %>
      </div>
    </div>
  </body>

  <footer class="w3-container w3-center w3-white w3-xlarge footer" style="height:10%">
    <a href="http://facebook.com/gojekindonesia"><i class="fa fa-facebook-official"></i></a>
    <a href="http://twitter.com/gojekindonesia"><i class="fa fa-twitter"></i></a>
    <a href="http://instagram.com/gojekindonesia/"><i class="fa fa-instagram"></i></a>
    <a href="http://youtube.com/channel/UCmlKSK0OKn_B3oPwElW4n5w"><i class="fa fa-youtube"></i></a>
    <p class="w3-medium" style="margin:0">
    © 2017 GO-SCHOLAR Ruby on Rails
    </p>
  </footer>
</html>

drivers/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div>
      <%= f.label :origin %>
      <%= f.text_field :origin %>
    </div><br>

    <div>
      <%= f.label :destination %>
      <%= f.text_field :destination %>
    </div><br>

    <div>
      <%= f.label :payment_type, 'Payment Type' %>
      <%= f.select :payment_type, Order.payment_types.keys %>
    </div><br>

    <div>
      <%= f.label :service, 'Service Type' %>
      <%= f.collection_select :service_id, Service.all, :id, :service_type %>
    </div><br>

    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>
<br>

drivers/app/views/orders/index.html.erb
<h1>History</h1>

<% if !@orders.blank? %>
  <table style="text-align: center">
    <tr>
      <th width="22%">Origin</th>
      <th width="22%">Destination</th>
      <th width="22%">Payment Type</th>
      <th width="22%">Distance</th>
      <th width="22%">Price</th>
    </tr>
    <% @orders.each do |order| %>
      <% if order.driver_id == session[:driver_id] %>
        <tr>
          <td><%= order.origin %></td>
          <td><%= order.destination %></td>
          <td><%= order.payment_type %></td>
          <td><%= order.distance %> km</td>
          <td><%= number_to_currency(order.price, unit: "Rp ", delimiter: ".", separator: ",") %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
<% else %>
  Seems you don't have any history.
<% end %>

drivers/app/views/orders/new.html.erb
<h1>Order GO-JEK</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

drivers/app/views/orders/show.html.erb
<h1>Order Details</h1>

<p>
  <strong>Origin:</strong>
  <%= @order.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @order.destination %>
</p>

<p>
  <strong>Payment Type:</strong>
  <%= @order.payment_type %>
</p>

<p>
  <strong>Service Type:</strong>
  <%= @order.service.service_type %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @order.distance %> km
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@order.price, unit: "Rp ", delimiter: ".", separator: ",") %>
</p>

<%= link_to 'Back', orders_path %>